### ISSUE TITLE
Devolución

### ISSUE THREAD

**Issue by MatiToledo** [giulianaerro/geopet-react#1]
Hola Giuli como andas ? Estuve viendo la page y esta muy bienn, solo note un par de cositas minimas que estaría bueno ver para que quede 10/10

- El pop up para reportar la mascota al principio no lo vi porque aparece en un lugar medio raro, tipo tuve que scrollear para abajo para poder verlo
- Agregaría algún estilo de carga en los botones que hacen algo que lleva tiempo para que el usuario sepa que esta ocurriendo algo (como por ejemplo al pedir la ubicación)
- En mis mascotas aunque no tenga mascotas reportadas aparece el "No publicaste mascotas" pero automáticamente se actualiza a "Mis mascotas reportadas"
- En la card de mis mascotas el boton de editar esta mal ubicado
- Y estaria bueno que al editar una mascota en los input ya aparezcan con los valores de la mascota para así no tener que completar todo de nuevo 

Eso seria todo, son muchas cosas pero chiquitas que se pueden ver rapido y hacen que la pagina quede un poco mas pulida. Pero de todas maneras esta excelente.

**Comment by giulianaerro** [comment]
Hola mati! gracias por la devolución, creo que ya están todos los cambios. Avisame cualquier cosa. Saludos!
